import Navbar from "@/components/Navbar";
import IntlPolyfills from "@/components/initPolyfills";
import { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { ReactNode } from "react";
import "../globals.css"
const locales = ["en", "bn"];
export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}
export const metadata: Metadata = {
  title: "Next Internationalization App",
  description: "Generated by Next Internationalization app",
};
export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: ReactNode;
  params: { locale: string };
    }) {
    let messages;

    try {
      messages = (await import(`../../messages/${locale}.json` as string)).default;
    } catch (error) {
      notFound();
    }
  return (
    <html lang={locale}>
      <body>
              <NextIntlClientProvider locale={locale} messages={messages}>
                  <Navbar/>
          {children}
          {/* <IntlPolyfills /> */}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
